# Generated by Django 3.1.4 on 2021-01-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210102_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleblogpage',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articleblogpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
