# Generated by Django 3.1.4 on 2021-01-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210103_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleblogpage',
            name='date_published',
            field=models.DateField(blank=True, null=True, verbose_name='Date article published'),
        ),
    ]
