# Generated by Django 3.1.4 on 2021-01-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210102_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='About_section_text',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='About_section_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
