# Generated by Django 3.1.4 on 2021-01-03 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('home', '0008_auto_20210103_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='coverstory_blog',
            field=models.ForeignKey(blank=True, help_text='Blog which is selected as coverstory', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Coverstory blog'),
        ),
    ]
