# Generated by Django 3.1.4 on 2021-01-03 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('home', '0009_homepage_coverstory_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featuredPost1_blog',
            field=models.ForeignKey(blank=True, help_text='First featured blog', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Featured blog 1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featuredPost2_blog',
            field=models.ForeignKey(blank=True, help_text='Second featured blog', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Featured blog 2'),
        ),
    ]
