# Generated by Django 3.1.4 on 2021-01-04 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('blog', '0014_articleblogpage_date_published'),
        ('home', '0010_auto_20210103_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='coverstory_discription',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='coverstory_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featuredPost1_author',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featuredPost1_category',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featuredPost1_date',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featuredPost1_discription',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featuredPost1_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featuredPost1_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featuredPost2_author',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featuredPost2_category',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featuredPost2_date',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featuredPost2_discription',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featuredPost2_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featuredPost2_title',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='blog_listing_section',
            field=models.ForeignKey(blank=True, help_text='First blog listing section for the homepage. Will display up to five child items.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Blog listing section'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='coverstory_blog',
            field=models.ForeignKey(blank=True, help_text='Blog which is selected as coverstory', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.blogdetailpage', verbose_name='Coverstory blog'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='featuredPost1_blog',
            field=models.ForeignKey(blank=True, help_text='First featured blog', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.blogdetailpage', verbose_name='Featured blog 1'),
        ),
    ]
